services:
  rails:
    build: .
    ports:
      - "3000:80"
    volumes:
      - .:/rails
      - bundle:/usr/local/bundle
    environment:
      # - RAILS_ENV=development/
      - SECRET_KEY_BASE=eec57a9266cc24b34bac42804c3184176bc83a725b1eece8ad20b413c67f89f6a4c6be50e91919280c423e8aa962383f8a3c676b9c3c40611449410dee3c7e27
  db:
    image: postgres:15-alpine
    container_name: academy_quest_db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - academy_quest_data:/var/lib/postgresql/data
volumes:
  bundle:
  academy_quest_data:
